### ISSUE TITLE
Cryptographic hash of Connector certificate not included in the Self-description

### ISSUE THREAD

**Issue by jfernandezsqs** [International-Data-Spaces-Association/DataspaceConnector#34]
In the requirements of the DSC it is specified that the self-description of the connector must have the cryptographic hash of Connector certificate.
I have deployed a DSC version 6.2.0 and this is the response body I am obtaining from the connector using the Swagger UI 
Connector GET /Public IDS self-description
[DSC_self-description.docx](https://github.com/International-Data-Spaces-Association/DataspaceConnector/files/7807813/DSC_self-description.docx)

Also, this is the response body obtained using the Swagger UI Connector GET /api/connector Private IDS self-description
[DSC_private_self-description.docx](https://github.com/International-Data-Spaces-Association/DataspaceConnector/files/7807980/DSC_private_self-description.docx)

It does not appear the cryptographic hash of Connector certificate.
How can I configure the DSC so that this information appears in the self-description?
Thanks in advance

**Comment by ghost** [comment]
The `publicKey` of the `config.json` was not persisted in the database, which is why it was no longer present from the second start when using a persistent database, since from then on the displayed configuration was generated based on the database information. This has been fixed in the meantime. However, the hash must currently be specified manually in `config.json` before start.

(fixed on main, v8.0.0)
