### ISSUE TITLE
Mismatch of DB (table: data, column: id) between flyway migration script and building db via hibernate

### ISSUE THREAD

**Issue by SebastianOpriel** [International-Data-Spaces-Association/DataspaceConnector#463]
_Bug: NOT NULL constraint for id field must be removed from flyway migration scripts. It is intended that after a contract is negotiated between two connectors, an empty data entity (table data) is created in database. The database shall create an id by itself. Unfortunately it seems, that NOT NULL constraint from an early v5.0.0. migration script of flyway avoids auto generation of id, as it expects the id to be set previously._

If flyway is enabled (https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/1957363bab5f3d98f1e849a8a76895fd5274480f/src/main/resources/application.properties#L135) to create the DB scheme, `data`-table's id column has `NOT NULL` constraint see 
https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/1957363bab5f3d98f1e849a8a76895fd5274480f/src/main/resources/db/migration/V5.0.0__Baseline.sql#L112

Export of table after creation:
```java
create table if not exists data
(
    dtype           varchar(31) not null,
    id              bigint not null primary key,
    deleted         boolean default false,
    localdata_value oid,
    access_url      varchar(2048)
);
```

If DB is created from scratch without flyway, the column seems to have no such constraint
https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/1957363bab5f3d98f1e849a8a76895fd5274480f/src/main/java/io/dataspaceconnector/model/artifact/Data.java#L64

Export of table after creation:
```java
create table if not exists data
(
    dtype           varchar(31) not null,
    id              bigserial
        primary key,
    deleted         boolean,
    localdata_value text,
    access_url      varchar(2048)
);
```
# Reproduce
Use docker-compose of MDS: https://github.com/Mobility-Data-Space/Deployment-Examples/blob/main/docker-test-environment/docker-compose.yml
Enable or Disable Flyway and try to consume a data source from another connector.

# Solution
- [ ] DB migration fix for v8 shall be created in separate file which removes NON NULL constraint from the id field https://github.com/International-Data-Spaces-Association/DataspaceConnector/tree/main/src/main/resources/db/migration

**Comment by omarsilva1** [comment]
From the [postgres documentation](https://www.postgresql.org/docs/current/sql-createtable.html):

> PRIMARY KEY enforces the same data constraints as a combination of UNIQUE and NOT NULL. 

It is not possible to drop the not null constraint from the id field, since it is a primary key. I tested it with a migration file including 
`ALTER TABLE public.data
    ALTER COLUMN id DROP NOT NULL;
`
I receive the following exceptions:
![image](https://user-images.githubusercontent.com/77329033/194945677-16b45141-fbb1-42e1-86ef-eeb622b38836.png)

I was testing this locally with a simplified version based on your configuration (I left out DAPS and security stuff) and realized an env field is missing (in case you enable flyway when testing):
`      - SPRING_FLYWAY_BASELINE_ON_MIGRATE=true/false`

https://github.com/Mobility-Data-Space/Deployment-Examples/blob/5a7fdd60d9e77297b64b3956569bf8dab952d851/docker-test-environment/docker-compose.yml#L39-L40




Adding this line to the environment fixed the exceptions that arise when you first start without flyway and then with (persisting an artifact worked fine as well). 

There are still exceptions that arise after persisting an artifact on a connector that was first started with flyway and then without.
`dataspaceconnector    | 2022-10-07T15:10:29,666 [https-jsse-nio-8080-exec-5] ERROR - ERROR: null value in column "id" of relation "data" violates not-null constraint\n  Detail: Failing row contains (RemoteData, null, f, null, https://localhost:8080/api/swagger-ui/in dex.html#/Artifacts/crea...).`

Can you confirm this is also the exception you were getting?

**Comment by omarsilva1** [comment]
The solution was not to remove the NOT NULL constraint but rather make the id auto increment and be automatically generated. The keyword bigserial (which is present without flyway) is a shorthand for that and was missing when starting the db with flyway. I've created a PR that fixes this issue.
