### ISSUE TITLE
Force reloading configuration does not update cached configuration in database

### ISSUE THREAD

**Issue by SebastianOpriel** [International-Data-Spaces-Association/DataspaceConnector#497]
If a connector is started via docker-compose (see e.g., https://github.com/Mobility-Data-Space/Deployment-Examples/tree/main/docker-test-environment) and additionally setting `configuration.force.reload=false` (resp. `CONFIGURATION_FORCE_RELOAD=TRUE`), values of config.json are just updated in self-description, but not in the database, accessible via Swagger UI or DSC UI (settings tab).

See related: https://github.com/Mobility-Data-Space/Deployment-Examples/issues/3

**Comment by ghost** [comment]
Note: May be related to the bug of the UI that the active configuration was not loaded but the 0th instead.
https://github.com/International-Data-Spaces-Association/DataspaceConnectorUI/issues/301

**Comment by ghost** [comment]
This will be due to the wrong/not active configuration details displayed in the UI. Should another configuration be active than the one used in the UI, the other not-displayed (active) config will be force-updated but the update is not visible in the UI since it uses and displays an other config. I have tested the force-reload in the DSC and could not find any error in the DSC itself for force reloading the config.

![image](https://user-images.githubusercontent.com/75306992/200540866-27ade80b-e11d-445c-8f1d-7f10cc0dda98.png)

Should the error occur again at some time, please just reopen the issue.
